export const GuardrailName = {
  Alinia: "alinia",
  AnyLlm: "any_llm",
  AzureContentSafety: "azure_content_safety",
  AzurePromptShields: "azure_prompt_shields",
  BedrockGuardrails: "bedrock_guardrails",
  BielikGuard: "bielik_guard",
  CompassJudger: "compass_judger",
  Deepset: "deepset",
  DuoGuard: "duo_guard",
  DynaGuard: "dyna_guard",
  FlowJudge: "flowjudge",
  GliGuard: "gli_guard",
  GliNerPii: "gli_ner_pii",
  Glider: "glider",
  GptOssSafeguard: "gpt_oss_safeguard",
  GraniteGuardian: "granite_guardian",
  HarmGuard: "harm_guard",
  InjecGuard: "injec_guard",
  Jasper: "jasper",
  KananaSafeguard: "kanana_safeguard",
  LakeraGuard: "lakera_guard",
  LettuceDetect: "lettuce_detect",
  LlamaGuard: "llama_guard",
  NemotronContentSafety: "nemotron_content_safety",
  OffTopic: "off_topic",
  OpenAIModeration: "openai_moderation",
  Pangolin: "pangolin",
  Patronus: "patronus",
  PolyGuard: "poly_guard",
  Prometheus: "prometheus",
  PromptGuard: "prompt_guard",
  ProtectAI: "protectai",
  Qwen3Guard: "qwen3_guard",
  Qwen3GuardStream: "qwen3_guard_stream",
  Selene: "selene",
  Sentinel: "sentinel",
  ShieldGemma: "shield_gemma",
  WatsonxGuardian: "watsonx_guardian",
  WildGuard: "wild_guard",
} as const;

export type GuardrailName = (typeof GuardrailName)[keyof typeof GuardrailName];

export const GUARDRAIL_NAMES = Object.freeze(Object.values(GuardrailName));
